export const types={
    addUser:"[gestion] add user to storange",
    errorUser:"[gestion] errors add user storange",
    deleteUser:"[gestion] delete user storange",
    addLideres:"[gestion] add liders storange",
    consultLeader:"[gestion] consult lider storange",
    cancelConsultLeader:"[gestion] calcel consult lider storange",
    addProjects:"[gestion] add projects to storange",

    addProject:"[gestion] add project to storange",
    addLider:"[interface] open modal lider to storange",
    addLeaders:"[gestion] add leaders to storange",
    addInfoProject:"[gestion] add name and description of project to storange",
    addProjectLeader:"[gestion] add project of leader to storange",
    addTotalActivities:"[gestion] add total activities of project",
    addTotalActivitiesFinish:"[gestion] add total activities of project finish",
    addPercentageActivitiesFinish:"[gestion] add percentage activities of project finish",
    addTotalTask:"[gestion] add total task",
    addPercentageTaskFinish:"[gestion] add percentage task of project finish",
    addGoalsProject:"[gestion] add goals of project",
    addCountsGoalsProject:"[gestion] add counts states goals of project",
    addGoal:"[gestion] add goal select of project",
    addActivitiesGoal:"[gestion] add activities of goal",
    addResponsables:"[gestion] add responsables of system",
    addActivity:"[gestion] add activity of project",
    addActivitiesInitials:"[gestion] add activities in status initial of project",
    addActivitiesOrganization:"[gestion] add activities in status organization of project",
    addActivitiesEjecution:"[gestion] add activities in status ejecution of project",
    addActivitiesFinish:"[gestion] add activities in status finish of project",
    addDataSpiProject:"[gestion] add data of SPI of the project",
    addDataCpiProject:"[gestion] add data of CPI of the project",
    addIdActivity:"[gestion] add id of activity of project",
    addInfomrationIndicators:"[gestion] add infomration of indicators to storange",

    addTaskActivities:"[gestion] add task of Activities",
    addTaskActivitiesInitials:"[gestion] add Task activities in status initial of project",
    addTaskActivitiesOrganization:"[gestion]  add Task activities in status organization of project",
    addTaskActivitiesEjecution:"[gestion] add Task activities in status ejecution of project",
    addTaskActivitiesFinish:"[gestion] add Task activities in status finish of project",

    addActivitiesPlanedFinish:"[gestion] add activities planed of project",
    addRecursosActivities:"[gestion] add recursos of activity",
    addTotalPresupuestoRecursosActivities:"[gestion] add total presupuesto recursos of activity",
    addTotalPresupuestoTareasActivities:"[gestion] add total presupuesto tareas of activity",
    addRecursoActivity:"[gestion] add recurso of activity",
    addPresupuestoActivity:"[gestion] add presupuesto of activity",

    addTaskPlaned:"[gestion] add task planed of activity",
    addRecursosTask:"[gestion] add recursos of task",
    addPresupuestoTareas:"[gestion] add total presupuesto of tareas",

    addPresupuestoMeta:"[gestion] add total presupuesto of metas",
    addIdMeta:"[gestion] add total id of metas",
    addMeta:"[gestion] add of metas",
    addIdLider:"[gestion] add of idLider",


    // INTERFACES
    createLeader : "[interface] open modal crear lider",
    closeLeader : "[interface] close modal crear lider",
    informationSPI : "[interface] open modal informationSPI",
    informationCPI : "[interface] open modal informationCPI",
    detailActivity : "[interface] open modal detail activity",
    detailRecurso : "[interface] open modal detail recurso",
    createRecurso : "[interface] open modal create recurso",
    deleteRecurso : "[interface] open modal delete recurso",
    deleteActivity : "[interface] open modal delete activity",
    detailTask : "[interface] open modal detail task",
    deleteTask: "[interface] open modal delete task",
    deleteGoal: "[interface] open modal delete goal",
    detailGoal : "[interface] open modal detail goal",
    deleteProject: "[interface] open modal delete project",
    detailProject: "[interface] open modal detail project",
    deleteLider: "[interface] open modal delete lider",
    detailLider: "[interface] open modal detail Lider",
};